apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zenbot
  template:
    metadata:
      labels:
        app: zenbot
    spec:
      containers:
      - name: zenbot
        imagePullPolicy: Never
        image: zenbot
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zenbot-secret
              key: openai-api-key
        resources: {}
        ports:
        - containerPort: 5000
          protocol: TCP
