apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenbot
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zenbot
  template:
    metadata:
      labels:
        app: zenbot
    spec:
      serviceAccount: zenbot
      containers:
      - name: zenbot
        imagePullPolicy: IfNotPresent
        image: localhost:5000/zenbot
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: zenbot-secret
              key: openai-api-key
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 8
        ports:
        - containerPort: 5000
          protocol: TCP
